"""Convert Gemma 4 GGUF model files to HuggingFace safetensors format.

Gemma 4 uses an advanced Gemma 2-style architecture with sliding window / global attention 
interleaving, and adds native multimodal capabilities (vision and audio encoders).
This script:
  - Maps standard LLM tensors to Gemma 2/4 HF names (including 4x RMSNorms per layer).
  - Handles GGUF shape reversal (Fortran -> C-order).
  - Applies norm-1.0 convention handling.
  - Copies missing vision/audio encoder tensors from the reference model.
  - Handles tied embeddings if applicable.
"""

from __future__ import annotations

import argparse
import sys
import re
from pathlib import Path

import numpy as np
import torch
from gguf import GGUFReader

from common import (
    copy_reference_files,
    decode_gguf_tensor,
    load_converted_tensors,
    load_reference_shapes,
    write_shards,
)

_MAX_DISPLAY = 30

# --- Gemma 4 Tensor Mappings ---

GLOBAL_MAP = {
    "token_embd.weight": "model.embed_tokens.weight",
    "output_norm.weight": "model.norm.weight",
    "output.weight": "lm_head.weight",
}

# Fixed: Use correct llama.cpp GGUF layer suffixes for Gemma dual-norm architecture
LAYER_SUFFIX_MAP = {
    "attn_norm.weight": "input_layernorm.weight",
    "attn_post_norm.weight": "post_attention_layernorm.weight",
    "ffn_norm.weight": "pre_feedforward_layernorm.weight",
    "ffn_post_norm.weight": "post_feedforward_layernorm.weight",
    "attn_q.weight": "self_attn.q_proj.weight",
    "attn_k.weight": "self_attn.k_proj.weight",
    "attn_v.weight": "self_attn.v_proj.weight",
    "attn_output.weight": "self_attn.o_proj.weight",
    "ffn_gate.weight": "mlp.gate_proj.weight",
    "ffn_up.weight": "mlp.up_proj.weight",
    "ffn_down.weight": "mlp.down_proj.weight",
}

def gguf_name_to_hf(name: str) -> str | None:
    """Map a GGUF tensor name to its HuggingFace equivalent for Gemma 4."""
    if name in GLOBAL_MAP:
        return GLOBAL_MAP[name]
    m = re.match(r"blk\.(\d+)\.(.*)", name)
    if m:
        layer, suffix = m.group(1), m.group(2)
        if suffix in LAYER_SUFFIX_MAP:
            return f"model.layers.{layer}.{LAYER_SUFFIX_MAP[suffix]}"
    return None

def _is_missing_tensor(hf_name: str) -> bool:
    """Check if a tensor name belongs to multimodal encoders or buffers (absent from GGUF)."""
    lower = hf_name.lower()
    # Vision and audio towers are not stored in the text GGUF
    if "vision" in lower or "audio" in lower:
        return True
    # Ignore RoPE inv_freq buffers which are dynamically generated by HF
    if "inv_freq" in lower or "rope" in lower:
        return True
    return False

def apply_conventions(hf_name: str, tensor: torch.Tensor) -> torch.Tensor:
    """Apply Gemma-specific conventions to decoded tensors.
    
    GGUF (llama.cpp) stores Gemma RMSNorm weights centered around 1.0 (w + 1.0).
    HuggingFace computes Gemma2RMSNorm as x * (1.0 + weight), so it expects 
    weights centered around 0.0. We subtract 1.0 to restore the HF convention.
    """
    if "norm.weight" in hf_name or "layernorm.weight" in hf_name:
        orig_dtype = tensor.dtype
        tensor = (tensor.float() - 1.0).to(orig_dtype)
    return tensor

def convert(
    gguf_path: str,
    ref_dir: str,
    output_dir: str,
    shard_size_mb: int = 4500,
    keep_fp16: bool = False,
):
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    print(f"Loading reference shapes from: {ref_dir}")
    ref_shapes = load_reference_shapes(ref_dir)

    print(f"Reading GGUF: {gguf_path}")
    reader = GGUFReader(gguf_path)
    gguf_tensors = reader.tensors
    print(f"GGUF: {len(gguf_tensors)} tensors")

    gguf_expected = {k: v for k, v in ref_shapes.items() if not _is_missing_tensor(k)}
    missing_in_gguf = {k: v for k, v in ref_shapes.items() if _is_missing_tensor(k)}
    
    print(f"GGUF-expected reference tensors: {len(gguf_expected)}")
    print(f"Missing (vision/audio/buffers) tensors to copy from reference: {len(missing_in_gguf)}")

    mapping = {}
    unmatched: list[tuple[str, str | None, str]] = []
    
    # 1. Map tensor names
    for gt in gguf_tensors:
        hf_name = gguf_name_to_hf(gt.name)
        if hf_name and hf_name in gguf_expected:
            mapping[gt.name] = hf_name
        elif hf_name:
            unmatched.append((gt.name, hf_name, "mapped but not in ref model (expected)"))
        else:
            unmatched.append((gt.name, None, "no mapping rule"))

    if unmatched:
        print(f"\nERROR: {len(unmatched)} unmatched GGUF tensors:", file=sys.stderr)
        for name, hf, reason in unmatched[:_MAX_DISPLAY]:
            print(f"  {name} -> {hf} ({reason})", file=sys.stderr)
        sys.exit(1)

    mapped_count = len(mapping)
    print(f"Mapped: {mapped_count}/{len(gguf_tensors)}")

    hf_tensors = {}
    decode_errors = []
    
    # 2. Decode and apply conventions
    for gt in gguf_tensors:
        if gt.name not in mapping:
            continue
        hf_name = mapping[gt.name]
        try:
            # GGUF stores most linear weights in Fortran-order (column-major); 
            # reverse_shape=True safely converts to C-order (row-major) PyTorch layout.
            t = decode_gguf_tensor(gt, keep_f32=True, keep_f16=keep_fp16, reverse_shape=True)
            expected = gguf_expected[hf_name]
            
            # Align shape if needed (e.g. 1D vs 2D structural differences)
            if list(t.shape) != expected:
                if t.numel() == int(np.prod(expected)):
                    t = t.reshape(expected).contiguous()
                else:
                    decode_errors.append(
                        f"{gt.name} -> {hf_name}: got {list(t.shape)}, expected {expected}"
                    )
                    continue
            
            # Apply Gemma norm subtraction (-1.0)
            t = apply_conventions(hf_name, t)
            hf_tensors[hf_name] = t
            
        except Exception as e:
            decode_errors.append(f"{gt.name}: {e}")

    if decode_errors:
        print(f"\nERROR: {len(decode_errors)} tensor decode/shape errors:", file=sys.stderr)
        for msg in decode_errors[:_MAX_DISPLAY]:
            print(f"  {msg}", file=sys.stderr)
        sys.exit(1)

    # 3. Handle Tied Word Embeddings
    # If the original GGUF excluded the tied output.weight, clone it from token_embd.
    if "lm_head.weight" in gguf_expected and "lm_head.weight" not in hf_tensors:
        if "model.embed_tokens.weight" in hf_tensors:
            print("\nNotice: lm_head.weight not in GGUF, cloning from model.embed_tokens.weight (weight tying)")
            hf_tensors["lm_head.weight"] = hf_tensors["model.embed_tokens.weight"].clone()

    # 4. Verify GGUF Coverage
    missing_from_conversion = [k for k in gguf_expected if k not in hf_tensors]
    if missing_from_conversion:
        print(f"\nERROR: {len(missing_from_conversion)} GGUF-expected tensors not produced:", file=sys.stderr)
        for name in missing_from_conversion[:_MAX_DISPLAY]:
            print(f"  {name}  {gguf_expected[name]}", file=sys.stderr)
        if len(missing_from_conversion) > _MAX_DISPLAY:
            print(f"  ... and {len(missing_from_conversion) - _MAX_DISPLAY} more", file=sys.stderr)
        sys.exit(1)

    # 5. Copy missing vision/audio tensors from reference model
    if missing_in_gguf:
        print(f"\nCopying {len(missing_in_gguf)} multimodal/buffer tensors from reference model...")
        ref_tensors = load_converted_tensors(ref_dir)
        copied = 0
        for hf_name in sorted(missing_in_gguf):
            if hf_name in ref_tensors:
                hf_tensors[hf_name] = ref_tensors[hf_name]
                copied += 1
            else:
                # Buffers like inv_freq may not be in safetensors, which is completely fine
                if "inv_freq" not in hf_name and "rope" not in hf_name:
                    print(f"  WARNING: reference tensor {hf_name} not found in safetensors", file=sys.stderr)
        print(f"Copied {copied} / {len(missing_in_gguf)} missing tensors from reference")

    print(f"\nConverted: {len(hf_tensors)} total tensors")

    # 6. Write to disk
    copy_reference_files(ref_dir, output)
    write_shards(hf_tensors, output, shard_size_mb=shard_size_mb)

def main():
    parser = argparse.ArgumentParser(
        description="Convert Gemma 4 GGUF to safetensors"
    )
    parser.add_argument("--gguf", required=True)
    parser.add_argument(
        "--reference-model",
        required=True,
        help="Path to base model safetensors directory for name/shape mapping",
    )
    parser.add_argument("--output", required=True)
    parser.add_argument("--shard-size-mb", type=int, default=4500)
    parser.add_argument("--keep-fp16", action="store_true")
    args = parser.parse_args()
    
    convert(
        args.gguf,
        args.reference_model,
        args.output,
        shard_size_mb=args.shard_size_mb,
        keep_fp16=args.keep_fp16,
    )

if __name__ == "__main__":
    main()
